USE [master]
GO

/****** Object:  Database [ProjectManager]    Script Date: 17-06-2019 15:44:31 ******/
CREATE DATABASE [ProjectManager]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ProjectManager', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\ProjectManager.mdf' , SIZE = 102400KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ProjectManager_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\ProjectManager_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ProjectManager] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ProjectManager].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ProjectManager] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ProjectManager] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ProjectManager] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ProjectManager] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ProjectManager] SET ARITHABORT OFF 
GO

ALTER DATABASE [ProjectManager] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ProjectManager] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ProjectManager] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ProjectManager] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ProjectManager] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ProjectManager] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ProjectManager] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ProjectManager] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ProjectManager] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ProjectManager] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ProjectManager] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ProjectManager] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ProjectManager] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ProjectManager] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ProjectManager] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ProjectManager] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ProjectManager] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ProjectManager] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ProjectManager] SET RECOVERY FULL 
GO

ALTER DATABASE [ProjectManager] SET  MULTI_USER 
GO

ALTER DATABASE [ProjectManager] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ProjectManager] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ProjectManager] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ProjectManager] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ProjectManager] SET  READ_WRITE 
GO


